### ISSUE TITLE
Dependabot: TypeScript 7 is blocked by tsup's bundled rollup-plugin-dts

### ISSUE THREAD

**Issue by Fanzzzd** [Fanzzzd/convex-logto#102]
Findings from triaging Dependabot PR #87 (`typescript 5.8.3 → 7.0.2`), verified in a clean clone of that branch.

## 1. Our source needs one small fix (worth landing regardless)

TS 7 typechecks the whole workspace cleanly **except** two errors, both from the same root:

```
src/webhooks.ts(415,52): error TS2345: Argument of type 'Uint8Array<ArrayBufferLike>' is not
assignable to parameter of type 'string | BufferSource'.
```

`BoundedBodyResult.bytes` is an unparameterized `Uint8Array`, i.e. `Uint8Array<ArrayBufferLike>`, and `BufferSource` excludes `SharedArrayBuffer`. Pinning the buffer type (`bytes: Uint8Array<ArrayBuffer>` in `src/component/http_body.ts`) fixes both; the value is already constructed as `new Uint8Array(byteLength)`, so nothing else changes. Valid on TS 5.7+, so it is forward-compatible today.

## 2. The build is the actual blocker

With that fix, `tsc --noEmit` passes on 7.0.2 and the build still dies:

```
TypeError: Cannot read properties of undefined (reading 'useCaseSensitiveFileNames')
    at .../rollup-plugin-dts@6.1.1_.../rollup-plugin-dts.cjs
    at .../tsup@8.5.1/dist/rollup.js:4857:37
```

`rollup-plugin-dts@6.5.1` does declare `typescript: "^4.5 || ^5 || ^6 || ^7"`, but tsup **bundles** 6.1.1 into its own `dist/rollup.js`, so a `pnpm.overrides` entry has no effect — I tried it and the same bundled copy still ran. tsup 8.5.1 is the current latest, so there is no release to move to yet.

## Proposal

- Land the `Uint8Array<ArrayBuffer>` fix now (no behavior change, unblocks the type side).
- Ignore TypeScript **major** updates in `.github/dependabot.yml` with a comment pointing here, and close #87.
- Revisit when tsup ships a build with `rollup-plugin-dts` ≥ 6.5.

## Related: `@react-native-async-storage/async-storage` (#99)

Same class of "CI-green but wrong" bump. Expo SDK 56 pins `@react-native-async-storage/async-storage` to **2.2.0** in `bundledNativeModules.json`; #99 proposes 3.1.1. Nothing in CI builds native code, so `verify` passes while `npx expo install --check` would flag it — exactly what the `expo` / `expo-*` / `react-native` ignores added in #93 exist to prevent. It should be added to that ignore list and #99 closed.
